### ISSUE TITLE
Only registered cloud is published livox mid-360

### ISSUE THREAD

**Issue by FPSychotic** [hku-mars/Point-LIO#19]
hi, I have point-lio odometry working without any fine tunning, but it looks working very good. 
My problem is I cannot get a dense pointcloud as only  registered cloud is being published. 

thanks
![Screenshot from 2023-04-06 18-27-41](https://user-images.githubusercontent.com/36112212/230452579-97e37bb0-a4db-4386-91b9-36897515911a.png)
![Screenshot from 2023-04-06 18-27-53](https://user-images.githubusercontent.com/36112212/230452583-7046e9a9-582b-4f23-bc81-5930cab2932e.png)

**Comment by Joanna-HE** [comment]
Thanks for your interest in our work! For your information, the parameters are not needed to be fine tuned, excepting those are related to IMU, since the point-lio is designed to be robust to IMU saturation, those parameters should be modified according to the IMU you use. 

And there is not a dense map produced by the Point-LIO yet, since the Point-LIO registers a lidar point into the map after it calculates the robot localization at the exact sampling time of this lidar point. For those points that are not processed, the accurate localization is not obtained. Maybe a function for inaccurate dense map could be added into the Point-LIO in the near future.

**Comment by FPSychotic** [comment]
Ohh, I see, in my opinion is totally normal there is not dense pointcloud as it is a odometry package, the only thing that made me think in that was a YouTube video and some pictures,where looked dense at my eyes, but maybe it was other package with Point-lio as odometry root.
It is very light for CPU, you did a great job , thanks by share it.

**Comment by FPSychotic** [comment]
Ohh, I see, in my opinion is totally normal there is not dense pointcloud as it is a odometry package, the only thing that made me think in that was a YouTube video and some pictures,where looked dense at my eyes, but maybe it was other package with Point-lio as odometry root.
It is very light for CPU, you did a great job , so smart

**Comment by FPSychotic** [comment]
ohh, discovered going outdoors it will show the map just like fast-lio does, that kind of map is what I was looking for, It is what I understand by dense, but maybe technically is other thing.
